server:
  port: 9125
  contextPath: /payment-service
logging:
  file: d://temp/payment-service.log
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
security:
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyUri: http://localhost:8085/auth/oauth/token_key
config:
    oauth2:
        client-id: service-account-1
        client-secret: service-account-1-secret
        access-token-url: http://localhost:8085/auth/oauth/token
        userAuthorizationUri: http://localhost:8085/auth/oauth/authorize
        resourceURI: localhost:9115/payment-service/payment/quote